# st_secrets.toml

[palm_api_key]
    palm_api_key = "AIzaSyCsm_P-rRiW6AJ5WN7wk4fitPjr3K8KkFQ"

[palm_api]
api_key = "AIzaSyCsm_P-rRiW6AJ5WN7wk4fitPjr3K8KkFQ"

[palm_api_key]
    value = "AIzaSyCsm_P-rRiW6AJ5WN7wk4fitPjr3K8KkFQ"

palm ="AIzaSyCsm_P-rRiW6AJ5WN7wk4fitPjr3K8KkFQ"
